-- =================================================================
-- SECCIÓN 1: PERFILES DE USUARIO
-- =================================================================

CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name TEXT,
    avatar_url TEXT
);


-- =================================================================
-- SECCIÓN 2: SISTEMA DE ROLES
-- =================================================================

CREATE TABLE roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE user_roles (
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    role_id UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);


-- =================================================================
-- SECCIÓN 3: AUTOMATIZACIÓN EN LA CREACIÓN DE USUARIOS
-- =================================================================

INSERT INTO roles (name, description) VALUES
('admin', 'Administrador con acceso total a la plataforma.'),
('customer', 'Cliente, rol por defecto para nuevos usuarios.');

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  v_default_role_id UUID;
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url)
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );

  SELECT id INTO v_default_role_id FROM public.roles WHERE name = 'customer';

  IF v_default_role_id IS NOT NULL THEN
    INSERT INTO public.user_roles (user_id, role_id)
    VALUES (new.id, v_default_role_id);
  END IF;
  
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==============================
-- ENUMS
-- ==============================
CREATE TYPE condition_type AS ENUM ('New', 'Semi-New', 'Used');
CREATE TYPE fuel_type AS ENUM ('Gasoline', 'Diesel', 'Hybrid', 'Electric');
CREATE TYPE traction_type AS ENUM ('FWD', 'RWD', 'AWD', '4WD'); -- tracción
CREATE TYPE transmission_type AS ENUM ('Manual', 'Automatic', 'CVT', 'Semi-Automatic');

-- ==============================
-- TABLAS DE MARCAS Y MODELOS
-- ==============================
CREATE TABLE brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    sort_order UNIQUE NOT NULL
);

CREATE TABLE models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    sort_order UNIQUE NOT NULL,
    UNIQUE (brand_id, name),
    UNIQUE (brand_id, sort_order)
);

-- ==============================
-- TABLA PRINCIPAL DE AUTOS
-- ==============================
CREATE TABLE cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT NOT NULL REFERENCES models(id) ON DELETE CASCADE,
    price NUMERIC NOT NULL,
    image_urls TEXT[] NOT NULL,
    mileage SMALLINT NOT NULL CHECK (mileage >= 0),
    year SMALLINT NOT NULL CHECK (year >= 1900 AND year <= EXTRACT(YEAR FROM CURRENT_DATE) + 1),
    fuel fuel_type NOT NULL,
    edition TEXT NOT NULL,
    color TEXT NOT NULL,
    traction traction_type NOT NULL,
    condition condition_type NOT NULL,
    transmission transmission_type NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- ==============================
-- TABLA DE CONFIGURACIÓN PARA EL HOME PAGE
-- ==============================

CREATE TABLE home_page_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_banner_url TEXT NOT NULL,
    b2b_benefits_url TEXT NOT NULL,
    b2c_benefits_url TEXT NOT NULL,
    faqs JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT singleton_check CHECK (id = 1)
);

-- ==============================
-- INSERTAR DATOS DE EJEMPLO
-- ==============================

INSERT INTO home_page_config (id, hero_banner_url, b2b_benefits_url, b2c_benefits_url, faqs)
VALUES (
    1,
    'https://placehold.co/1920x1080/000000/FFFFFF?text=Hero+Banner',
    'https://placehold.co/800x600/CCCCCC/000000?text=Beneficios+B2B',
    'https://placehold.co/800x600/EEEEEE/000000?text=Beneficios+B2C',
    '[
        {
            "question": "¿Qué tipo de financiamiento ofrecen?",
            "answer": "Ofrecemos múltiples opciones de financiamiento que se adaptan a tus necesidades. Puedes consultar más detalles en nuestra sección de financiamiento o contactando a un asesor."
        },
        {
            "question": "¿Puedo entregar mi auto actual como parte de pago?",
            "answer": "¡Claro que sí! Aceptamos vehículos como parte del pago. Realizaremos una evaluación justa y transparente de tu auto para ofrecerte el mejor valor posible."
        },
        {
            "question": "¿Todos los vehículos tienen garantía?",
            "answer": "Sí, todos nuestros vehículos, tanto nuevos como seminuevos, vienen con una garantía completa para tu tranquilidad. Los términos y la duración pueden variar según el modelo y la condición."
        }
    ]'::jsonb
);